### ISSUE TITLE
better usage explanation and ideas

### ISSUE THREAD

**Issue by matu3ba** [jonatan-branting/better-n.nvim#2]
As I understand it, this makes me loose the functionality to continue the previous stored search result.
For example, if I have searched for all exact occurrences with `*` for word `/\<example\>`, `n` will not continue searching for `/\<example\>` after I have registered another action under `n`.

is this correct?

Ideas:
1. Do you have a plan or idea how to enable the user to save and restore this search info?
2. This looks related to a modal configuration, which means to have a different set of static or dynamic configurations under keypress (by entering a mode): https://github.com/Iron-E/nvim-libmodal
* Do you have an idea how to simplify the approach? libmodal is rather cumbersome to get a fast setup like emacs
3. Do you have any idea how to solve https://github.com/linty-org/key-menu.nvim/issues/10, which would be useful for this plugin as (optional) user-info for the current binding?

**Comment by jonatan-branting** [comment]
Hey!

It is correct that if you search for `/\<example\>` using `*`, `n` will be assigned to function like `n` normally does (i.e. go to the next match). If you then use another registered mapping, `n` will be reassigned to another function. This might indeed not suit some workflows, but I have found that I rarely use `/` (or a similar mapping) for the same search term across movement commands that I have personally registered. 

If you then press `//` again for example, `n` will again be reassigned dynamically.

With regards to your ideas:
1. This is already saved by Vim, and to reinitiate a search that has been "overwritten", just use `//<cr>`, which will search for the latest searched for term, and remap `n` to function like expected.
2. I would agree the concepts are related, but they are still quite different. This plugin is also smaller in scope, only tackling "search" or "jump" commands. Although you could of course use this for other purposes as well, by using completely different bindings. Regarding the sub-question, I do think there is room for more exploration in Vim for conditional or dynamic bindings (i.e. do what you mean), which is something I might explore more in the future, but I have no immediate plans.
3. I did not realize this was an issue, but after some quick testing, it indeed is. I will have to do some research here, thanks for reporting it! (And thanks for linking the related issue in `key-menu.nvim`, lots of relevant information there)

**Comment by jonatan-branting** [comment]
Regarding your second question, the rather newly released https://github.com/anuvyklack/hydra.nvim seems to be exactly what you're looking for.

Other than that, I'm closing this issue, as I've fixed the issue pointed out in your third question. They were aware of a solution for the `key-menu.nvim` which basically entails doing the same thing I did in this commit: https://github.com/jonatan-branting/nvim-better-n/commit/b7d83c6ea9f452b18a995f8da1a44121a6160ef8 (i.e. basically save the count when you can access it to use it later)
