### ISSUE TITLE
insert `1<Plug>(better-n)f` accidentally.

### ISSUE THREAD

**Issue by MKrbm** [jonatan-branting/better-n.nvim#5]
Currently, I'm mapping `fl` to `f` and `fh` to `F`.  Therefore, I setup config as below.

![image](https://github.com/jonatan-branting/nvim-better-n/assets/57752203/74a02c9e-e25d-458b-992a-594bf69d6798)

It turs out to work expected except when I push somethings like `fa`, `fs`, `fi` which insert a string `1<Plug>(better-n)f`.

![image](https://github.com/jonatan-branting/nvim-better-n/assets/57752203/4219a36d-9c58-48de-a694-209b68409377)

Thank you. I really like this plugin so far.

**Comment by jonatan-branting** [comment]
Thanks for the issue!

I'm not sure exactly how I'd solve this, but it happens due to `f` being override twice. It's kind of edge-casey though, as you'd never be able to jump to any instance of `l` or `h` with this setup.

It's something that's indeed not working as you'd expect, though.

**Comment by jonatan-branting** [comment]
This should be solved with #10, although you will need to modify your configuration to work with the new version. (Sorry about that!)
