### ISSUE TITLE
Overrides which-key descriptions

### ISSUE THREAD

**Issue by justyn** [jonatan-branting/better-n.nvim#9]
Hi, thanks for putting your plugin online, I really like the idea.

One problem I'm having is that any keybindings registered with better_n lose their [which-key](https://github.com/folke/which-key.nvim) description.

So for example I have many mappings that start with [ or ] (I'm using largely the AstroNvim default).

But if I register any with better_n, they get the default label "better_n_remap".

Here is the which-key menu that appears after typing "[", before enabling better_n.

![image](https://github.com/jonatan-branting/nvim-better-n/assets/203419/630476f8-a573-4aa0-914a-45a8de032c52)

And here is the same menu when better_n has been installed and some of the "[" keybindings have been registered with it:

![image](https://github.com/jonatan-branting/nvim-better-n/assets/203419/5cef69ce-d9bd-4e1c-92fd-e7aeff04fa19)

Here is the "next git hunk" mapping in the default AstroNvim config:

`  maps.n["]g"] = { function() require("gitsigns").next_hunk() end, desc = "Next Git hunk" }`

Is there any way to pass through the "desc" field when using better_n, in order for which-key to still be useful?

Thanks

**Comment by jonatan-branting** [comment]
This should be solved with #10, although you will need to modify your configuration to work with the new version. (Sorry about that!)
